services:
  payload:
    tty: true
    stdin_open: true
    image: node:22.18.0-alpine
    working_dir: /home/node/app

    ports:
      - "8890:8890"

    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    command:
      - sh
      - -c
      - |
        apk add --no-cache tmux \
        && npm install pnpm -g \
        && pnpm install \
        && tmux new-session -d -s app 'pnpm dev' \
        && tmux a -t app \; set-option status off | grep -v '^[[:space:]]*$'
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - PORT=8890
    # prevent crash from taking it down 
    restart: unless-stopped

  postgres:
    image: postgres:latest
    restart: always
 #   ports:
 #     - "5432:5432"
    environment:
      POSTGRES_USER:      ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB:        ${POSTGRES_DB:-kollab-payload-template}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  node_modules:
