import tailwindcssAnimate from 'tailwindcss-animate'
import typography from '@tailwindcss/typography'

/** @type {import('tailwindcss').Config} */
const config = {
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  darkMode: ['selector', '[data-theme="dark"]'],
  plugins: [tailwindcssAnimate, typography],
  prefix: '',
  safelist: [
    'lg:col-span-4',
    'lg:col-span-6',
    'lg:col-span-8',
    'lg:col-span-12',
    'border-border',
    'bg-card',
    'border-error',
    'bg-error/30',
    'border-success',
    'bg-success/30',
    'border-warning',
    'bg-warning/30',
    // Background colors
    'bg-primary',
    'bg-secondary',
    'bg-tertiary',
    'bg-base',
    'bg-accent',
    'bg-accenttwo',
    'bg-accentthree',
    'bg-border',
    'bg-neutral',
    'bg-neutraltwo',
    'bg-highlight',
    'bg-highlighttwo',
    // Text colors
    'text-primary',
    'text-secondary',
    'text-tertiary',
    'text-base',
    'text-accent',
    'text-accenttwo',
    'text-accentthree',
    'text-border',
    'text-neutral',
    'text-neutraltwo',
    'text-highlight',
    'text-highlighttwo',
    // Border colors
    'border-primary',
    'border-secondary',
    'border-tertiary',
    'border-base',
    'border-accent',
    'border-accenttwo',
    'border-accentthree',
    'border-neutral',
    'border-neutraltwo',
    'border-highlight',
    'border-highlighttwo',
    // Hover background colors
    'hover:bg-primary',
    'hover:bg-secondary',
    'hover:bg-tertiary',
    'hover:bg-base',
    'hover:bg-accent',
    'hover:bg-accenttwo',
    'hover:bg-accentthree',
    'hover:bg-border',
    'hover:bg-neutral',
    'hover:bg-neutraltwo',
    'hover:bg-highlight',
    'hover:bg-highlighttwo',
    // Hover text colors
    'hover:text-primary',
    'hover:text-secondary',
    'hover:text-tertiary',
    'hover:text-base',
    'hover:text-accent',
    'hover:text-accenttwo',
    'hover:text-accentthree',
    'hover:text-border',
    'hover:text-neutral',
    'hover:text-neutraltwo',
    'hover:text-highlight',
    'hover:text-highlighttwo',
    // Hover border colors
    'hover:border-primary',
    'hover:border-secondary',
    'hover:border-tertiary',
    'hover:border-base',
    'hover:border-accent',
    'hover:border-accenttwo',
    'hover:border-accentthree',
    'hover:border-neutral',
    'hover:border-neutraltwo',
    'hover:border-highlight',
    'hover:border-highlighttwo',
  ],
  theme: {
    container: {
      center: true,
      padding: {
        '2xl': '2rem',
        DEFAULT: '1rem',
        lg: '2rem',
        md: '2rem',
        sm: '1rem',
        xl: '2rem',
      },
      screens: {
        '2xl': '86rem',
        lg: '64rem',
        md: '48rem',
        sm: '40rem',
        xl: '80rem',
      },
    },
    extend: {
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },

      colors: {
        primary: 'var(--primary)',
        secondary: 'var(--secondary)',
        tertiary: 'var(--tertiary)',
        base: 'var(--base)',
        highlight: 'var(--highlight)',
        highlighttwo: 'var(--highlighttwo)',
        accent: 'var(--accent)',
        accenttwo: 'var(--accenttwo)',
        accentthree: 'var(--accentthree)',
        border: 'var(--border)',
        neutral: 'var(--neutral)',
        neutraltwo: 'var(--neutraltwo)',
      },
      fontFamily: {
        sans: ['Montserrat', 'sans-serif'],
      },
      fontSize: {
        display: [
          '4.375rem',
          { lineHeight: 'normal', fontWeight: '700', textTransform: 'uppercase' },
        ],
        h1: ['3.125rem', { lineHeight: 'normal', fontWeight: '700', textTransform: 'uppercase' }],
        h2: ['2.1875rem', { lineHeight: 'normal', fontWeight: '700', textTransform: 'uppercase' }],
        h3: ['1.375rem', { lineHeight: 'normal', fontWeight: '400' }],
        h3Hover: [
          '1.375rem',
          { lineHeight: 'normal', fontWeight: '400', textDecoration: 'underline' },
        ],
        h4: ['1.125rem', { lineHeight: 'normal', fontWeight: '600' }],
        body: ['1rem', { lineHeight: '1.5rem', fontWeight: '400' }],
        bodySemibold: ['1rem', { lineHeight: 'normal', fontWeight: '600' }],
        bodyUnderline: [
          '1rem',
          { lineHeight: '1.375rem', fontWeight: '600', textDecoration: 'underline' },
        ],
        helper: ['0.875rem', { lineHeight: 'normal', fontWeight: '400' }],
        button: ['1.125rem', { lineHeight: 'normal', fontWeight: '700' }],
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      typography: () => ({
        DEFAULT: {
          css: [
            {
              '--tw-prose-body': 'var(--text)',
              '--tw-prose-headings': 'var(--text)',
              h1: {
                fontWeight: 'normal',
                marginBottom: '0.25em',
              },
            },
          ],
        },
      }),
    },
  },
}

export default config
