import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

// Migration: drop problematic collection tables so they can be recreated cleanly.
// NOTE: This intentionally preserves the `media` table and related media data.
export async function up({ db }: MigrateUpArgs): Promise<void> {
  // Safety: refuse to run destructive migration unless explicitly allowed.
  // Set ALLOW_DESTRUCTIVE_SCHEMA_CHANGES=true in the environment to opt-in.
  if (process.env.ALLOW_DESTRUCTIVE_SCHEMA_CHANGES !== 'true') {
    throw new Error(
      'Refusing to run destructive migration. Set ALLOW_DESTRUCTIVE_SCHEMA_CHANGES=true to allow this.',
    )
  }

  await db.execute(sql`
    -- Drop Pages related tables (locales, version tables, helper tables)
    DROP TABLE IF EXISTS "pages_hero_links_locales" CASCADE;
    DROP TABLE IF EXISTS "_pages_v_version_hero_links_locales" CASCADE;
    DROP TABLE IF EXISTS "pages_hero_links" CASCADE;
    DROP TABLE IF EXISTS "pages_locales" CASCADE;
    DROP TABLE IF EXISTS "_pages_v_version_hero_links" CASCADE;
    DROP TABLE IF EXISTS "_pages_v_locales" CASCADE;
    DROP TABLE IF EXISTS "_pages_v" CASCADE;
    DROP TABLE IF EXISTS "pages" CASCADE;

    -- Drop Posts related tables
    DROP TABLE IF EXISTS "posts_locales" CASCADE;
    DROP TABLE IF EXISTS "_posts_v_locales" CASCADE;
    DROP TABLE IF EXISTS "_posts_v" CASCADE;
    DROP TABLE IF EXISTS "posts" CASCADE;

    -- Drop Categories related tables
    DROP TABLE IF EXISTS "categories_locales" CASCADE;
    DROP TABLE IF EXISTS "_categories_v_locales" CASCADE;
    DROP TABLE IF EXISTS "_categories_v" CASCADE;
    DROP TABLE IF EXISTS "categories" CASCADE;

    -- Drop People/Users related content if desired (no media removal)
    DROP TABLE IF EXISTS "people_locales" CASCADE;
    DROP TABLE IF EXISTS "_people_v_locales" CASCADE;
    DROP TABLE IF EXISTS "_people_v" CASCADE;
    DROP TABLE IF EXISTS "people" CASCADE;

    -- Drop globals (header/footer/branding) tables if they exist. Naming may vary;
    -- IF EXISTS makes these safe no-ops when the table doesn't exist.
    DROP TABLE IF EXISTS "globals_header" CASCADE;
    DROP TABLE IF EXISTS "globals_footer" CASCADE;
    DROP TABLE IF EXISTS "globals_branding" CASCADE;

    -- Clean up common indices/sequences if any linger (optional, safe with IF EXISTS)
    DROP INDEX IF EXISTS "pages_slug_idx";
    DROP INDEX IF EXISTS "posts_slug_idx";
    DROP INDEX IF EXISTS "pages_hero_hero_media_idx";
    DROP INDEX IF EXISTS "_pages_v_version_hero_version_hero_media_idx";
  `)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  // Safety: do not automatically recreate schema in production. This is a no-op
  // unless explicitly allowed so someone doesn't accidentally reintroduce
  // destructive changes in the production/staging run.
  if (process.env.ALLOW_DESTRUCTIVE_SCHEMA_CHANGES !== 'true') return

  // Intentionally left blank: recreating the full original schema requires
  // exact column definitions and enum types which should be generated by
  // Payload's migration/CLI tooling or restored from a committed migration JSON.
  // If you want, I can add SQL to recreate the tables exactly as before —
  // tell me and I'll scaffold that from the existing migration JSON files.
  await db.execute(sql`
    -- no-op: manual/auto-generated migration should recreate these tables
  `)
}
